/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela.java
 *
 * Created on 10/10/2012, 20:31:58
 */

package br.com.fiap.sugestao.tela;

import br.com.fiap.sugestao.grafo.CustomSimpleWeightedGraph;
import br.com.fiap.sugestao.grafo.MyWeightEdge;
import java.io.IOException;
import org.jgrapht.graph.SimpleWeightedGraph;
import br.com.fiap.sugestao.InOut.VisitacaoInOut;
import br.com.fiap.sugestao.Visitacao.Perfil;
import br.com.fiap.sugestao.Visitacao.Produto;
import br.com.fiap.sugestao.Visitacao.Visitacao;
import br.com.fiap.sugestao.grafo.Aresta;
import br.com.fiap.sugestao.grafo.Vertice;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jgraph.JGraph;
import org.jgraph.graph.DefaultCellViewFactory;
import org.jgraph.graph.GraphLayoutCache;
import org.jgrapht.ext.JGraphModelAdapter;
import org.jgrapht.graph.DefaultWeightedEdge;
import org.jgraph.layout.CircleGraphLayout;
import org.jgraph.layout.JGraphLayoutAlgorithm;
import org.jgrapht.alg.ChromaticNumber;
/**
 *
 * @author Leandro Boni
 */

public class Tela extends javax.swing.JFrame {

    /** Creates new form Tela */
    public Tela() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 422));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sugestão"));

        jLabel1.setText("Idade:");

        jLabel2.setText("Sexo:");

        jTextField1.setColumns(3);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Feminino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField2.setColumns(7);

        jLabel3.setText("Sugestao 1:");

        jLabel4.setText("Sugestão 2:");

        jLabel5.setText("Sugestão 3:");

        jTextField3.setColumns(7);

        jTextField4.setColumns(7);

        jButton1.setText("Sugerir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Visitação"));

        jLabel6.setText("Idade:");

        jLabel7.setText("Sexo:");

        jTextField5.setColumns(3);

        jLabel8.setText("Produto:");

        jTextField6.setColumns(7);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Masculino");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Feminino");

        jButton2.setText("Adicionar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);

        jButton3.setText("Organizar Grafo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        boolean ok = true;
        
        if((!this.jRadioButton3.isSelected() && !this.jRadioButton4.isSelected()) || this.jTextField5.getText().isEmpty() || this.jTextField6.getText().isEmpty())
        { 
            JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos.");
            ok = false;
        }
        try
        {
            Integer aux = Integer.parseInt(this.jTextField5.getText());
        }catch(Exception ex1)
        {
            ok = false;
            JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos com números inteiros!!");
        }       
        
        if(ok)
        {
            Produto produto = new Produto();
            produto.setCodigo(Integer.parseInt(this.jTextField6.getText()));
            String sexo = "";
            if(this.jRadioButton3.isSelected())
                sexo = "M";
            else
                sexo = "F";
            Visitacao visitacao = new Visitacao(produto,Integer.parseInt(this.jTextField5.getText()),sexo);
            VisitacaoInOut inout = new VisitacaoInOut(caminho);
            inout.IncluirVisitacao(visitacao);

            geraGrafo();

            this.jScrollPane1.setViewportView(graph);

            this.invalidate();
            this.repaint();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        boolean ok = true;
        
        if((!this.jRadioButton1.isSelected() && !this.jRadioButton2.isSelected()) || this.jTextField1.getText().isEmpty())
        { 
            JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos.");
            ok = false;
        }
        try
        {
            Integer aux = Integer.parseInt(this.jTextField1.getText());
        }catch(Exception ex1)
        {
            ok = false;
            JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos com números inteiros!!");
        }       
        
        if(ok)
        {
            ArrayList<Aresta> arestas = new ArrayList<Aresta>();
            String sexo = "";
            if(this.jRadioButton1.isSelected())
                sexo = "M";
            else
                sexo = "F";

            Perfil perfil = new Perfil(Integer.parseInt(this.jTextField1.getText()),sexo);
            if(g.containsVertex(perfil.getPerfil()));
            {
                Set<DefaultWeightedEdge> set = g.edgesOf(perfil.getPerfil());

                for(DefaultWeightedEdge edge : set)
                {
                    int rounded = (int) Math.round(g.getEdgeWeight(edge));
                    arestas.add(new Aresta(String.valueOf(g.getEdgeSource(edge)),String.valueOf(g.getEdgeTarget(edge)),rounded));
                }
                // Em ordem crescente do início do mandato  
                Collections.sort (arestas, new Comparator() {  
                    @Override
                    public int compare(Object o1, Object o2) {  
                        Aresta a1 = (Aresta) o1;  
                        Aresta a2 = (Aresta) o2;  
                        return a1.getPeso() < a2.getPeso() ? +1 : (a1.getPeso() > a2.getPeso() ? -1 : 0);  
                    }  
                });

                this.jTextField2.setText("");
                this.jTextField3.setText("");
                this.jTextField4.setText("");
                
                int contador = 1;
                for(Aresta aresta : arestas)
                {
                    if(contador < 4)
                    {        
                        if(contador == 1)
                            this.jTextField2.setText(aresta.getPara().substring(1));
                        else if(contador == 2)
                            this.jTextField3.setText(aresta.getPara().substring(1));
                        else if(contador == 3)
                            this.jTextField4.setText(aresta.getPara().substring(1));
                        contador++;
                    }else
                         break;
                }
            }            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GraphLayoutCache layout = new GraphLayoutCache(adapter, new DefaultCellViewFactory());
        graph.setGraphLayoutCache(layout);
        JGraphLayoutAlgorithm alg = new CircleGraphLayout();
        alg.run(graph, JGraphModelAdapter.getAll(adapter));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        final Tela tela = new Tela();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    JFileChooser fc = new JFileChooser();    
                    int option = fc.showOpenDialog(new JPanel());    
                    if (option == JFileChooser.APPROVE_OPTION) {  
                        File file = fc.getSelectedFile();  
                        caminho = file.getCanonicalPath();  
                    }
                }catch(IOException ex1)
                {
                    //JOptionPane.showMessageDialog(new JFrame(),"Houveram problemas ao ler o arquivo!!");                                    
                }

                if(caminho.isEmpty())
                {
                    JOptionPane.showMessageDialog(new JFrame(),"Houveram problemas ao ler o arquivo!!");
                }else
                {
                    geraGrafo();
                    tela.jScrollPane1.setViewportView(graph);
                    tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    tela.setVisible(true);
           
                }
            }
        });
    }
    public static void geraGrafo()
    {
        g = new CustomSimpleWeightedGraph(MyWeightEdge.class); 

        //Lendo Visitacoes
        VisitacaoInOut inout = new VisitacaoInOut(caminho);

        ArrayList<Visitacao> visitacoes	= inout.LerVisitacoes();

        //Buscando Vertices
        Vertice vertice = new Vertice();
        HashSet<Vertice> vertices = vertice.getVertices(visitacoes);

        //Buscando Arestas
        Aresta aresta = new Aresta();
        ArrayList<Aresta> arestas = aresta.getArestas(visitacoes);

        //Preenchendo os Vertices
        for(Vertice vert : vertices)
        {
            g.addVertex(vert.getVertice());
        }

        //Preenchendo as Arestas
        for(Aresta ar : arestas)
        {
            DefaultWeightedEdge edge = (DefaultWeightedEdge)g.addEdge(ar.getDe(),ar.getPara());
            g.setEdgeWeight(edge,ar.getPeso());
        }

        adapter = new JGraphModelAdapter(g);

        graph = new JGraph(adapter);

        graph.isDragEnabled();
        
        graph.setAutoResizeGraph(true);

        // Control-drag should clone selection
        graph.setCloneable(true);

        // Enable edit without final RETURN keystroke
        graph.setInvokesStopCellEditing(true);

        // When over a cell, jump to its default port (we only have one, anyway)
        graph.setJumpToDefaultPort(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    static SimpleWeightedGraph g; 
    static JGraphModelAdapter adapter;
    static JGraph graph;
    static String caminho = "";
}
